experiment_name: areal-1.5B-distill-gpus-8
trial_name: 1024x8
mode: ray
wandb:
  mode: disabled
recover_mode: auto
recover_retries: 10
allocation_mode: 'sglang.d4p1m1+d4p1m1'
n_nodes: 1
n_gpus_per_node: 8
cache_clear_freq: 1
exp_ctrl:
  total_train_epochs: 10
  save_freq_epochs: 1
  ckpt_freq_secs: 600
torch_cache_mysophobia: true
actor:
  type:
    _class: qwen2
  path: '/storage/models/DeepSeek-R1-Distill-Qwen-1.5B'
  optimizer:
    lr: 1.0e-05
    lr_scheduler_type: constant
    initial_loss_scale: 262144.0
    loss_scale_window: 5.0
    hysteresis: 2
  sglang:
    disable_radix_cache: true
    context_length: 18432
    mem_fraction_static: 0.8
    max_running_requests: 128
critic:
  type:
    _class: qwen2
    is_critic: true
  path: '/storage/models/DeepSeek-R1-Distill-Qwen-1.5B'
  init_critic_from_actor: true
ref:
  type:
    _class: qwen2
  path: '/storage/models/DeepSeek-R1-Distill-Qwen-1.5B'
actor_train:
  mb_spec:
    max_tokens_per_mb: 19456
critic_train:
  mb_spec:
    max_tokens_per_mb: 19456
actor_gen:
  mb_spec:
    max_tokens_per_mb: 19456
critic_inf:
  mb_spec:
    max_tokens_per_mb: 19456
actor_inf:
  mb_spec:
    max_tokens_per_mb: 19456
ref_inf:
  mb_spec:
    max_tokens_per_mb: 19456
dataset:
  path: '/storage/datasets/prompts_for_r1_distilled_0319.jsonl'
  max_prompt_len: 2048
  train_bs_n_seqs: 1024
ppo:
  gen:
    max_new_tokens: 16384
    min_new_tokens: 0
    top_p: 1.0
    top_k: 1000000
    temperature: 1.0
  ppo_n_minibatches: 4
  kl_ctl: 0.001
  discount: 1.0
  value_eps_clip: 0.2
  disable_value: true
  reward_output_scaling: 5.0
  reward_output_bias: 0.0
  adv_norm: true
  value_norm: true
group_size: 8
group_adv_norm: false
external_configs:
  cluster_config:
    fileroot: "/storage/ray/experiments"
  envs:
    REAL_GPU_MEMORY_KILL_THRESHOLD: "1"
