# Basic experiment info
experiment_name: test-exp
trial_name: test-trial
seed: 1
mode: ray
wandb:
  mode: disabled
  entity: null
  project: null
  name: null
  job_type: null
  group: null
  notes: null
  tags: null
  config: null
tensorboard:
  path: null

exp_ctrl:
  total_train_epochs: 5
  save_freq_epochs: 1
  save_freq_steps: null
  save_freq_secs: null
  ckpt_freq_epochs: null
  ckpt_freq_steps: null
  ckpt_freq_secs: 600
  eval_freq_epochs: null
  eval_freq_steps: null
  eval_freq_secs: null
  benchmark_steps: null
  benchmark_n_seqs: null

# Allocation and parallelism
allocation_mode: sglang.d4p1m1+d2p2m1
n_nodes: 1
n_gpus_per_node: 8

# Cluster configuration
ray_temp_path: /tmp/ray
cluster:
  cluster_name: local
  fileroot: /tmp/arealite/
  n_nodes: 32
  n_gpus_per_node: 8
  name_resolve:
    type: nfs
    nfs_record_root: /tmp/arealite/llm_server/

# Model
trainer:
  type: ppo
  ppo:
    actor:
      type:
        _class: qwen3
      path: /storage/testing/models/Qwen__Qwen3-1.7B/
      init_from_scratch: false
      gradient_checkpointing: true
      bf16: false
      optimizer:
        type: adam
        lr: 2.0e-05
        weight_decay: 0.05
        beta1: 0.9
        beta2: 0.95
        eps: 1.0e-05
        min_lr_ratio: 0.0
        lr_scheduler_type: constant
        warmup_steps_proportion: 0.001
        initial_loss_scale: 4294967296.0
        min_loss_scale: 1.0
        loss_scale_window: 5.0
        hysteresis: 2
        gradient_clipping: 1.0
    mb_spec:
      max_tokens_per_mb: 30720
    dataset:
      path: /storage/testing/datasets/boba_106k_0319.jsonl
      max_prompt_len: 1024
      train_bs_n_seqs: 512
    # Rollout
    collector:
      type: llm
      agent:
        type: math_code_single_step
        math_code_single_step:
          gconfig:
            n: 1
            max_new_tokens: 27648
            min_new_tokens: 0
            greedy: false
            top_p: 1.0
            top_k: 1000000
            temperature: 1.0
          tokenizer_path: /storage/testing/models/Qwen__Qwen3-1.7B/
      env:
        type: math_code_single_step
        reward_scaling: 5.0
        reward_bias: -0.5
        math_code_single_step:
          dataset_path: /storage/testing/datasets/boba_106k_0319.jsonl
    # Algorithm
    group_size: 16
    ppo_n_minibatches: 4
    eps_clip: 0.2
    c_clip: null
    value_eps_clip: 0.2
    early_stop_imp_ratio: 5.0
    actor_sample_reuse: 1
    critic_sample_reuse: 1
    max_reward_clip: 20.0
    reward_output_scaling: 5.0
    reward_output_bias: 0.0
    fuse_rew_ref: true
    discount: 1.0
    gae_lambda: 1.0
    adv_norm: true
    kl_ctl: 0.0
    use_adaptive_kl_ctl: false
    disable_value: true
    recompute_logprob: true
    use_decoupled_loss: true
    behav_imp_weight_cap: null

